### ISSUE TITLE
Error loading MHY APi Key

### ISSUE THREAD

**Issue by Gernardkam** [GoneTone/genshin-impact-wish-gacha-analyzer#1]
![Error](https://user-images.githubusercontent.com/80535011/110962491-0788d480-838c-11eb-92e6-9125266628cd.PNG)

Hi, I'm facing the problem as attached above whereby when I try to load other UID into the software, it display that MHY API key can't be load.

**Comment by GoneTone** [comment]
We will do further testing.

**Comment by GoneTone** [comment]
You need to reopen Wish history after switching accounts.
