### ISSUE TITLE
支援Linux? | Support Linux ?

### ISSUE THREAD

**Issue by SiongSng** [GoneTone/genshin-impact-wish-gacha-analyzer#10]
你好，想請問這款軟體是否會支援Linux，我看這款軟體是透過electron進行開發的，應該可以做得到？，但是目前原神是不支援Linux的但是可以透過Wine來正常執行，如果這款程式支援Linux可以透過自己選擇原神的數據儲存位置來使用嗎？

**Comment by GoneTone** [comment]
原神不支援 Linux，所以我們就沒開發那部份了，也只編譯 Windows 版本。

**Comment by SiongSng** [comment]
OK
