### ISSUE TITLE
執行後顯示取得資源失敗：timeout of 20000ms exceeded

### ISSUE THREAD

**Issue by saravaio18** [GoneTone/genshin-impact-wish-gacha-analyzer#14]
訊息為
網址 "https://webstatic.mihoyo.com/hk4e/gacha_info/os_asia/items/en-us.json" 取得資源失敗：timeout of 20000ms exceeded

**Comment by GoneTone** [comment]
此訊息是您讀取超時，請檢察網路並且嘗試看看使用瀏覽器是否能開啟那網址。
