### ISSUE TITLE
字体无法辨认

### ISSUE THREAD

**Issue by cckvin23** [GoneTone/genshin-impact-wish-gacha-analyzer#2]
![image](https://user-images.githubusercontent.com/80894507/111619360-6e8d0a00-8820-11eb-9254-feab5462f5f3.png)
我下载的是无需安装的版本

**Comment by GoneTone** [comment]
已修正：https://github.com/GoneTone/genshin-impact-wish-gacha-analyzer/commit/05dc7fc941809549ab08fe955f5a5fa337b6221a

请更新至版本 v0.2.5
https://github.com/GoneTone/genshin-impact-wish-gacha-analyzer/releases/tag/v0.2.5

感谢您的回报！
