### ISSUE TITLE
卡池歷史紀錄 API 資料取得失敗

### ISSUE THREAD

**Issue by isatempura** [GoneTone/genshin-impact-wish-gacha-analyzer#31]
由3.8到3.9也是這樣.
我想,應該是操作問題.可以告訴我錯在那裡嗎?謝謝

**Comment by GoneTone** [comment]
能截圖一下嗎，我確認一下

**Comment by isatempura** [comment]
![image](https://user-images.githubusercontent.com/96970731/147868570-21c5c761-c012-43d0-b3c2-9b883802ec57.png)

**Comment by GoneTone** [comment]
嘗試重新開啟遊戲，然後開啟遊戲內卡池歷史紀錄頁面，然後再重新加載看看，試試看可不可以

**Comment by hointat123** [comment]
![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png)
新版無法讀取API

**Comment by GoneTone** [comment]
> ![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png) 新版無法讀取API

我測試是正常的

**Comment by dream6179** [comment]
第一次顯示讀取API錯誤，再按一次就跳回原本的介面，但資料都是停留在7天前

**Comment by GoneTone** [comment]
> 第一次顯示讀取API錯誤，再按一次就跳回原本的介面，但只有常駐祈願有更新

@dream6179 重新在遊戲內打開卡池歷史紀錄，然後再刷新

**Comment by hointat123** [comment]
> > ![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png)新版無法讀取API
> 
> @hointat123我測試是正常的

不行,一直API資料讀取失敗,重新下載也不行,不知道怎麼回事

**Comment by GoneTone** [comment]
> > > ![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png)新版無法讀取API
> > 
> > 
> > @hointat123我測試是正常的
> 
> 不行,一直API資料讀取失敗,重新下載也不行,不知道怎麼回事

你是國際服還是陸服的

**Comment by hointat123** [comment]
> > > > ![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png)新版無法讀取API
> > > 
> > > 
> > > @hointat123我測試是正常的
> > 
> > 
> > 不行,一直API資料讀取失敗,重新下載也不行,不知道怎麼回事
> 
> 你是國際服還是陸服的？

國際服

**Comment by GoneTone** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png)新版無法讀取API
> > > > 
> > > > 
> > > > @hointat123我測試是正常的
> > > 
> > > 
> > > 不行,一直API資料讀取失敗,重新下載也不行,不知道怎麼回事
> > 
> > 
> > 你是國際服還是陸服的？
> 
> 國際服

有在遊戲內開啟卡池歷史紀錄嗎？ (每次開遊戲都要)

**Comment by hointat123** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png)新版無法讀取API
> > > > > 
> > > > > 
> > > > > @hointat123我測試是正常的
> > > > 
> > > > 
> > > > 不行,一直API資料讀取失敗,重新下載也不行,不知道怎麼回事
> > > 
> > > 
> > > 你是國際服還是陸服的？
> > 
> > 
> > 國際服
> 
> 有在遊戲內開啟卡池歷史紀錄嗎？ (每次開遊戲都要)

當然有阿,我在原神1.4版本開始使用,但前幾天突然讀取不到API

**Comment by GoneTone** [comment]
> > > > > > > ![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png)新版無法讀取API
> > > > > > 
> > > > > > 
> > > > > > @hointat123我測試是正常的
> > > > > 
> > > > > 
> > > > > 不行,一直API資料讀取失敗,重新下載也不行,不知道怎麼回事
> > > > 
> > > > 
> > > > 你是國際服還是陸服的？
> > > 
> > > 
> > > 國際服
> > 
> > 
> > 有在遊戲內開啟卡池歷史紀錄嗎？ (每次開遊戲都要)
> 
> 當然有阿,我在原神1.4版本開始使用,但前幾天突然讀取不到API

因為我們測試都是正常的...
不確定問題為何

之前都正常對吧，在那之後您有對電腦做過什麼變更之類的嗎，例如安裝防毒軟體等等的？

**Comment by hointat123** [comment]
> > > > > > > > ![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png)新版無法讀取API
> > > > > > > 
> > > > > > > 
> > > > > > > @hointat123我測試是正常的
> > > > > > 
> > > > > > 
> > > > > > 不行,一直API資料讀取失敗,重新下載也不行,不知道怎麼回事
> > > > > 
> > > > > 
> > > > > 你是國際服還是陸服的？
> > > > 
> > > > 
> > > > 國際服
> > > 
> > > 
> > > 有在遊戲內開啟卡池歷史紀錄嗎？ (每次開遊戲都要)
> > 
> > 
> > 當然有阿,我在原神1.4版本開始使用,但前幾天突然讀取不到API
> 
> 因為我們測試都是正常的... 不確定問題為何
> 
> 之前都正常對吧，在那之後您有對電腦做過什麼變更之類的嗎，例如安裝防毒軟體等等的？

沒有

**Comment by GoneTone** [comment]
> > > > > > > > > ![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png)新版無法讀取API
> > > > > > > > 
> > > > > > > > 
> > > > > > > > @hointat123我測試是正常的
> > > > > > > 
> > > > > > > 
> > > > > > > 不行,一直API資料讀取失敗,重新下載也不行,不知道怎麼回事
> > > > > > 
> > > > > > 
> > > > > > 你是國際服還是陸服的？
> > > > > 
> > > > > 
> > > > > 國際服
> > > > 
> > > > 
> > > > 有在遊戲內開啟卡池歷史紀錄嗎？ (每次開遊戲都要)
> > > 
> > > 
> > > 當然有阿,我在原神1.4版本開始使用,但前幾天突然讀取不到API
> > 
> > 
> > 因為我們測試都是正常的... 不確定問題為何
> > 之前都正常對吧，在那之後您有對電腦做過什麼變更之類的嗎，例如安裝防毒軟體等等的？
> 
> 沒有

能否錄影一下，整個操作步驟，包括打開遊戲歷史紀錄

**Comment by hointat123** [comment]
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/97159295/148192286-8a8ab2a7-8105-43f7-93f4-5db36d8efcbe.png)新版無法讀取API
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > @hointat123我測試是正常的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不行,一直API資料讀取失敗,重新下載也不行,不知道怎麼回事
> > > > > > > 
> > > > > > > 
> > > > > > > 你是國際服還是陸服的？
> > > > > > 
> > > > > > 
> > > > > > 國際服
> > > > > 
> > > > > 
> > > > > 有在遊戲內開啟卡池歷史紀錄嗎？ (每次開遊戲都要)
> > > > 
> > > > 
> > > > 當然有阿,我在原神1.4版本開始使用,但前幾天突然讀取不到API
> > > 
> > > 
> > > 因為我們測試都是正常的... 不確定問題為何
> > > 之前都正常對吧，在那之後您有對電腦做過什麼變更之類的嗎，例如安裝防毒軟體等等的？
> > 
> > 
> > 沒有
> 
> 能否錄影一下，整個操作步驟，包括打開遊戲歷史紀錄

影片太大了,我上傳了youtube了
https://youtu.be/jAWkYysjIOQ

**Comment by GoneTone** [comment]
@hointat123 你有沒有 Discord 或其他可以方便對話的聊天軟體，我後續會在幾個地方寫 Log 後 Build 一個版本讓你安裝，要用於 DEBUG

**Comment by hointat123** [comment]
> @hointat123 你有沒有 Discord 或其他可以方便對話的聊天軟體，我後續會在幾個地方寫 Log 後 Build 一個版本讓你安裝，要用於 DEBUG

![image](https://user-images.githubusercontent.com/97159295/148734401-398243a3-9754-43af-91ea-e327a87d561e.png)

**Comment by GoneTone** [comment]
已調查出問題，感謝 @hointat123 協助測試，問題將於 v0.3.10 版本修復。
