### ISSUE TITLE
載入出現亂碼

### ISSUE THREAD

**Issue by MazarineZ** [GoneTone/genshin-impact-wish-gacha-analyzer#32]
<a href="https://ibb.co/4jffmk0"><img src="https://i.ibb.co/9qvv8Pd/unknown.png" alt="unknown" border="0"></a><br />

在載入卡池紀錄的時候突然就顯示這一大串亂碼
請問這該如何解決

**Comment by GoneTone** [comment]
能把完整訊息發上來嗎，我看一下
