### ISSUE TITLE
無法讀取祈願紀錄

### ISSUE THREAD

**Issue by XCI9** [GoneTone/genshin-impact-wish-gacha-analyzer#39]
如下圖，
無法成功開啟祈願紀錄
也確定有在遊戲內開過歷史紀錄

不過我原神並不是裝在預設路徑，也就是系統碟
而是另一顆硬碟
不知道這會不會影響到log檔的抓取?

感謝
![image](https://user-images.githubusercontent.com/71249961/158316058-2fe39b56-fde9-4004-8c28-bbde66da21d0.png)

**Comment by GoneTone** [comment]
遊戲安裝位置並不影響。

您先開啟遊戲內歷史紀錄頁面，然後幫我確認看看 `%HomePath%\AppData\LocalLow\miHoYo\Genshin Impact` 路徑有沒有 `output_log.txt` 檔案，如果有請把檔案傳給我檢查看看 (傳至 p29022716@gmail.com ，因為 log 內可能會有一些不適合公開的資料)。
