### ISSUE TITLE
網址 "https://webstatic.mihoyo.com/hk4e/gacha_info/os_asia/items/zh-tw.json" 取得資源失敗：timeout of 20000ms exceeded

### ISSUE THREAD

**Issue by xd820410** [GoneTone/genshin-impact-wish-gacha-analyzer#4]
點擊更新資料後，
顯示正在取讀玩家的 常駐祈願 卡池歷史資料，
loading很久後顯示「網址 "https://webstatic.mihoyo.com/hk4e/gacha_info/os_asia/items/zh-tw.json" 取得資源失敗：timeout of 20000ms exceeded」

但此網址用chrome瀏覽器瀏覽可正常顯示json
版本0.3.1 & 0.3.4皆如此

**Comment by GoneTone** [comment]
我們這邊測試載入是正常的，您用瀏覽器開啟那頁面會花很久時間嗎？

**Comment by xd820410** [comment]
人在台灣，用Chrome開那頁體感是1～4秒，
暫時沒有頭緒沒關係，先當作特殊個案，
如果未來也有人有一樣的狀況，能推出大概是什麼方面的問題就可以了，
先謝謝啦～

**Comment by GoneTone** [comment]
目前還是一樣嗎，如果是可以試試看防毒軟體排除，測試看看是否為防毒軟體阻擋

**Comment by Ugio** [comment]
嗨嗨 我也遇到一樣的問題
剛剛試著改了語言再改回來就恢復正常了
