### ISSUE TITLE
只有活動池的紀錄沒更新

### ISSUE THREAD

**Issue by CanaleLime** [GoneTone/genshin-impact-wish-gacha-analyzer#40]
先感謝大大提供好用軟體!包括地圖跟統計真的都很方便~

我的狀況就跟標題一樣，就是我只有活動池的歷史紀錄沒有辦法更新，一直卡在前天，但常住池就沒問題，而且下方歷史紀錄中也有確實記錄到，就是不知道為什麼沒有轉換到活動角色統計的頁面。

感謝。

**Comment by CanaleLime** [comment]
目前有解決了，但原因不明xD 
我兩邊程式都開著，然後去過了一兩個任務再回來刷新就忽然可以了。

**Comment by GoneTone** [comment]
卡池紀錄不會立刻更新喔，會有 1 小時左右的延遲。
![image](https://user-images.githubusercontent.com/10025956/162609260-a6ed40d2-dd0d-4b3a-b7ac-fd3e98a3decf.png)
