### ISSUE TITLE
發生錯誤 無法讀取 Log 檔案，請確保您啟動過遊戲。

### ISSUE THREAD

**Issue by TiTi4869** [GoneTone/genshin-impact-wish-gacha-analyzer#41]
![image](https://user-images.githubusercontent.com/89084155/167913520-b3c805e6-5328-4335-8d85-5fa77c785d99.png)
如圖

**Comment by GoneTone** [comment]
您有先啟動遊戲並且開啟祈願歷史紀錄頁面嗎？ (每次都要)

**Comment by TiTi4869** [comment]
有的

**Comment by GoneTone** [comment]
您是國際服還是陸服？

**Comment by TiTi4869** [comment]
國際服(亞

**Comment by GoneTone** [comment]
我這邊測試是正常的哦...
您有辦法錄完整操作的影片給我確認一下嗎？
從開遊戲祈願歷史記錄頁面到開啟分析軟體

**Comment by GoneTone** [comment]
您先開啟遊戲內歷史紀錄頁面，然後幫我確認看看 `%HomePath%\AppData\LocalLow\miHoYo\Genshin Impact` 路徑有沒有 `output_log.txt` 檔案，如果有請把檔案傳給我檢查看看 (傳至 p29022716@gmail.com ，因為 log 內可能會有一些不適合公開的資料)。

**Comment by TiTi4869** [comment]
![image](https://user-images.githubusercontent.com/89084155/169496078-4d58adbe-93b8-47b2-b8d7-1d0599cd0243.png)

**Comment by GoneTone** [comment]
照理說就算改變安裝位置，原神資料還是會存在那個路徑，我也沒遇過這種狀況🤔

**Comment by TiTi4869** [comment]
還有辦法解決嗎QAQ

**Comment by GoneTone** [comment]
我目前沒有想法QQ

**Comment by TiTi4869** [comment]
好吧..

**Comment by GoneTone** [comment]
我有時間在研究看看，最近有點忙，很抱歉QQ

**Comment by apacheroger** [comment]
我一樣讀取不到 然後我找到記事本過後 搜尋 /log 結果搜尋不到 請問有救嗎
![image](https://user-images.githubusercontent.com/111950582/186333246-7eab219b-844b-4470-b4dd-d53af37e47e7.png)

**Comment by GoneTone** [comment]
最新版本改使用 Proxy 方式取得祈願卡池歷史記錄 API 網址，因為原神 3.0 版本已經無法從 Log 文件取得祈願卡池歷史記錄頁面網址，這版本測試看看！
https://github.com/GoneTone/genshin-impact-wish-gacha-analyzer/releases/tag/v0.5.0

**Comment by GoneTone** [comment]
剛剛發現有問題，撤回發佈版本...

**Comment by GoneTone** [comment]
> 最新版本改使用 Proxy 方式取得祈願卡池歷史記錄 API 網址，因為原神 3.0 版本已經無法從 Log 文件取得祈願卡池歷史記錄頁面網址，這版本測試看看！ https://github.com/GoneTone/genshin-impact-wish-gacha-analyzer/releases/tag/v0.5.0

v0.5.0 版本因有問題撤回發佈，v0.5.1 版本修復問題。
https://github.com/GoneTone/genshin-impact-wish-gacha-analyzer/releases/tag/v0.5.1
