### ISSUE TITLE
3.0改版後無法正常讀取

### ISSUE THREAD

**Issue by shony592** [GoneTone/genshin-impact-wish-gacha-analyzer#43]
這次改版整個歷史紀錄界面都有變動，似乎無法正常讀取，請問會修正嗎?

**Comment by GoneTone** [comment]
官方 log 檔在 3.0 版本不會記錄祈願歷史記錄頁面的網址了，導致無法取得 API 參數，目前我是有成功寫一個小測試專案利用其他方法取得，不過不算全自動，對一般使用者可能比較麻煩...

最近我也比較抽不出時間維護更新QQ

**Comment by GoneTone** [comment]
我是有打算重寫專案就是了XD

**Comment by GoneTone** [comment]
已發布版本 v0.5.0，這版本改使用 Proxy 方式取得祈願卡池歷史記錄 API 網址，因為原神 3.0 版本已經無法從 Log 文件取得祈願卡池歷史記錄頁面網址。
https://github.com/GoneTone/genshin-impact-wish-gacha-analyzer/releases/tag/v0.5.0

勉強抽出時間更新XD
專案重寫也正在進行中～

**Comment by GoneTone** [comment]
剛剛發現有問題，撤回發佈版本...

**Comment by GoneTone** [comment]
> 已發布版本 v0.5.0，這版本改使用 Proxy 方式取得祈願卡池歷史記錄 API 網址，因為原神 3.0 版本已經無法從 Log 文件取得祈願卡池歷史記錄頁面網址。 https://github.com/GoneTone/genshin-impact-wish-gacha-analyzer/releases/tag/v0.5.0
> 
> 勉強抽出時間更新XD 專案重寫也正在進行中～

v0.5.0 版本因有問題撤回發佈，v0.5.1 版本修復問題。
https://github.com/GoneTone/genshin-impact-wish-gacha-analyzer/releases/tag/v0.5.1
