### ISSUE TITLE
卡池數據丟失

### ISSUE THREAD

**Issue by Sammmmm1261** [GoneTone/genshin-impact-wish-gacha-analyzer#5]
之前有在用 0.2.1 - 0.3.1的免安裝版本，裡面有包含28/9 - 20/10的抽卡記錄

但是在更新至0.3.4之後，軟件重新讀取了遊戲內的抽卡記錄（21/10前的記錄已經清空），並導致更新0.3.4前的記錄全部消失。
這裡想請問是否有任何恢復數據的方法？謝謝。

**Comment by GoneTone** [comment]
抽卡紀錄官方並不會永久保留，只會存在 6 個月內的紀錄，本軟體目前只會抓取官方有的資料，並不會另外儲存記錄。

如果要保留歷史資料必須要另外存放，如果存放在使用者電腦內重灌或換電腦資料就沒了，如果存放在我們伺服器也是需要時間開發跟金費問題 (我沒有營利，單純靠贊助)，如果串 Google 雲端硬碟也是需要時間，而且不能確定官方資料格式是否會改變，所以我們才決定暫時不另外寫保留。
