### ISSUE TITLE
無法取得卡池歷史紀錄頁面網址，請確保您在遊戲內卡池開啟過歷史紀錄。

### ISSUE THREAD

**Issue by MHaoK1205** [GoneTone/genshin-impact-wish-gacha-analyzer#6]
我明明都開過了卡池歷史紀錄，但為什麼還是讀取不到，還是要用瀏覽器開啟歷史記錄，是的話是怎麼開？教教我

**Comment by GoneTone** [comment]
您是怎麼開啟卡池歷史紀錄的？

**Comment by MHaoK1205** [comment]
就開祈願後點在左下角的歷史記錄

**Comment by XMoiswnX** [comment]
遊戲中開啟歷史紀錄後，再點擊軟體的更新資料看看，如還有錯誤上傳錯誤圖片到這裡。

**Comment by leronube** [comment]
我有時也會發生，過一段時間再開程式後就會叫我進遊戲開卡池紀錄，按重新加載後就會卡在初始化。
解決方法 : 得再進遊戲祈願池開歷史紀錄，但關遊戲後有機率再發生。
![72f498fd8c43d71105c8cb8000af4ecc](https://user-images.githubusercontent.com/70561884/116655009-e40dfd80-a9bc-11eb-8d28-ee9dd19931e3.png)

**Comment by GoneTone** [comment]
@leronube 原神啟動後會清除原本的資料，導致軟體無法取得資料，每次啟動遊戲必須都要再開啟卡池記錄才能讀到資料。
