### ISSUE TITLE
發生錯誤 網址 "https://webstatic.mihoyo.com/hk4e/gacha_info/os_cht/items/en-us.json" 取得資源失敗：connect ECONNREFUSED 182.239.104.103:443

### ISSUE THREAD

**Issue by Lemon7777-p** [GoneTone/genshin-impact-wish-gacha-analyzer#7]
用瀏覽器開啟網址是正常的 (?)
後面ip是 400 Bad Request。
按重新加載後就會卡在初始化。
防毒只有windows defender（已允許執行）

https://user-images.githubusercontent.com/61228902/116774472-636c0180-aa8f-11eb-8dd1-4d851f2afc68.mp4

**Comment by Lemon7777-p** [comment]
https://webstatic.mihoyo.com/hk4e/gacha_info/os_cht/items/zh-tw.json也是報同一錯誤

**Comment by GoneTone** [comment]
確認一下，您的伺服器是不是台港澳？

**Comment by Lemon7777-p** [comment]
是台港澳

**Comment by GoneTone** [comment]
幫我測試看看防毒暫時停用是否能正確加載，我這邊測試是正常的

**Comment by Lemon7777-p** [comment]
並不能
![image](https://user-images.githubusercontent.com/61228902/116780893-dedeaa80-aab1-11eb-8de8-9ced4c959540.png)
